FORMAT: 1A
HOST: http://api.library.com/

# Library API
API quản lý sách đơn giản.

## Books Collection [/books]
### List All Books [GET]
+ Response 200 (application/json)
    + Attributes (array[Book])

## Data Structures
### Book (object)
+ id: 1 (number)
+ title: `Clean Code` (string)