summary: Tạo người dùng mới
tags:
  - Users
parameters:
  - name: body
    in: body
    required: true
    schema:
      $ref: "#/definitions/User"
responses:
  201:
    description: Created
    schema:
      $ref: "#/definitions/User"
